[machine]
ram_length = "256Mi"
user = "root"
entrypoint = "rollup-init /usr/local/bin/run_cartesapp debug"

[drives.root]
builder = "docker"
dockerfile = "rootfs.dockerfile"
build_args = ["OPERATOR_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"]
format = "ext2"
extra_size = "4Mb"
avoid_overwrite = "true"

[drives.app]
builder = "directory"
directory = "./core"
format = "sqfs"
mount = "/mnt/app/core"

[drives.misc]
builder = "directory"
directory = "./misc"
format = "sqfs"
avoid_overwrite = "true"
mount = "/mnt/app/misc"

[drives.cartridges]
builder = "empty"
size = "128Mb"
format = "ext2"
user = "dapp"

[drives.data]
builder = "empty"
size = "32Mb"
format = "ext2"
user = "dapp"
